### PR TITLE
Add patch for Windows AArch64 atomic jlong copying

### PR DESCRIPTION
**Pull request by swesonga**
The patch will be added by https://github.com/microsoft/openjdk-jdk21u/pull/18

### CODE REVIEW

**Comment by karianna** [comment]
@swesonga needs a rebase

**Comment by swesonga** [comment]
> @swesonga needs a rebase

My branch is based on the target branch (ms-patches/microsoft-patch-index) so my branch doesn't need rebasing. Our codeflow does not require ms-patches/microsoft-patch-index to be rebased either. Any thoughts on this, @d3r3kk?

**Comment by d3r3kk** [comment]
I don't _think_ it needs a rebase, judging by the state of the PR. However, it won't _hurt_ to rebase the two either, and there may be some reason for it that I cannot see at the moment - @karianna care to expound on this a bit?

**Comment by karianna** [comment]
My bad, I saw the merge conflict and immediately thought race condition.  What I really meant was 'solve the merge conflict as you see fit' :-)

**Comment by swesonga** [comment]
> My bad, I saw the merge conflict and immediately thought race condition. What I really meant was 'solve the merge conflict as you see fit' :-)

no worries. sorry for the confusion, I now see what you meant. I will rebase mine only.

**Review by brianjstafford — APPROVED** [review]
LGTM

**Pull request merged**
